name: Update Dependencies
on:
  push:
    branches: [ master ]
  schedule:
    # Every 15mins
    - cron: '15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.82.0
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
