---
name: Update Dependencies
on:
  push:
    branches:
      - main
  schedule:
    # Every 15mins
    - cron: '15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3.3.0
      - name: Run Renovate Bot
        uses: renovatebot/github-action@v34.154.4
        with:
          configurationFile: .github/workflows/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
